project:
  type: website

website:
  site-url: https://github.com/LYMDLUT/blogs
  title: "LYM 刘祎铭"
  navbar:
    right:
      - icon: github
        href: https://github.com/LYMDLUT
format:
  html: 
    theme: # https://quarto.org/docs/output-formats/html-themes.html
      light:
        - latera
        - brand
      dark:
        - darkly
        - brand
    css: styles.css

execute:
  freeze: auto
